---
- name: Ensure basic config
  hosts: all
  remote_user: root

  tasks:
    - name: Ensure hostname
      hostname:
        name: "{{ inventory_hostname }}"
  
    - name: Esure IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
        state: present
      with_items: "{{ groups.all }}"
    
    - name: Ensure updated system
      yum:
        name: "*"
        state: latest